
services:
  - name: docker:dind         # Testcontainers需要docker in docker
    command: ["--tls=false"]  # 禁用tls以避免docker启动中断

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:          # 作业的阶段列表及其执行顺序
  - build
  - test
  - deploy

build-job:       # 此作业在构建阶段运行，构建阶段是最先执行的
  image: gradle:7.4.1-jdk11-alpine
  stage: build
  script:
    - echo "开始编译代码..."
    - gradle clean compileJava
    - echo "编译代码完成..."

test-job:        # 此作业在测试阶段运行，测试阶段在第二阶段执行的
  image: gradle:7.4.1-jdk11-alpine
  stage: test
  script:
    -  echo "开始测试代码..."
    - gradle test --info
    - echo "测试代码完成..."

deploy-job:      # 此作业在部署阶段运行
  stage: deploy  # 只有当之前两个阶段都成功完成时，才会执行部署的。
  script:
    - echo "开始部署代码..."
    - echo "部署代码完成.."
